---
title: "2019 List of Lectures"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
intro <- list(
  title = "Introduction",
  topics = c("Course overview"),
  pdf = "",
  rmd = c("lectures/week_01/lec_01_class_overview.Rmd"),
  html = c("lectures/week_01/lec_01_class_overview.html"),
  background = c(""),
  youtube = ""
)

software <- list(
  title = "Overview of required software",
  topics = c("R", "RStudio", "R Markdown"),
  pdf = "",
  rmd = c("lectures/week_01/lec_02_software.Rmd"),
  html = c("lectures/week_01/lec_02_software.html"),
  background = c("[R software](https://www.r-project.org/about.html)", "[RStudio](https://resources.rstudio.com/)", "[Intro to R Markdown](https://rmarkdown.rstudio.com/lesson-1.html)"),
  youtube = ""
)

data_types <- list(
  title = "Ecological data and distributions",
  topics = c("Detections", "Counts", "Survival"),
  pdf = "",
  rmd = c("lectures/week_01/lec_03_data_types.Rmd"),
  html = c("lectures/week_01/lec_03_data_types.html"),
  background = c("[Statistical distributions](http://learnbayes.org/demo/stat-distributions-js/distributionTable.html)"),
  youtube = ""
)

linear_models_1 <- list(
  title = "Linear models",
  topics = c("Regression", "ANOVA", "ANCOVA"),
  pdf = "",
  rmd = c("lectures/week_02/lec_04_intro_to_linear_models.Rmd"),
  html = c("lectures/week_02/lec_04_intro_to_linear_models.html"),
  background = c(""),
  youtube = ""
)

linear_models_2 <- list(
  title = "Linear models",
  topics = c("Models in matrix form", "Least squares"),
  pdf = "",
  rmd = c("lectures/week_02/lec_05_intro_to_linear_models.Rmd"),
  html = c("lectures/week_02/lec_05_intro_to_linear_models.html"),
  background = c(""),
  youtube = ""
)

inference <- list(
  title = "Inference",
  topics = c("Variance partitioning", "F-tests for nested models", "Permutation tests"),
  pdf = "",
  rmd = c("lectures/week_02/lec_06_inference_from_linear_models.Rmd"),
  html = c("lectures/week_02/lec_06_inference_from_linear_models.html"),
  background = c(""),
  youtube = ""
)

diagnostics <- list(
  title = "Model diagnostics",
  topics = c("Model assumptions", "Leverage", "Outliers"),
  pdf = "",
  rmd = c("lectures/week_03/lec_07_diagnostics_for_linear_models.Rmd"),
  html = c("lectures/week_03/lec_07_diagnostics_for_linear_models.html"),
  background = c(""),
  youtube = ""
)

non_IID_errors <- list(
  title = "Problems with model residuals",
  topics = c("Weighted least squares", "Generalized least squares", "Robust regression", "Autocorrelated errors"),
  pdf = "",
  rmd = "lectures/week_03/lec_08_non-IID_errors.Rmd",
  html = "lectures/week_03/lec_08_non-IID_errors.html",
  background = "",
  youtube = ""
)

transformations <- list(
  title = "Data transformations",
  topics = c("Powers/roots", "Box-Cox", "Logarithms"),
  pdf = "",
  rmd = "lectures/week_03/lec_09_data_transformations.Rmd",
  html = "lectures/week_03/lec_09_data_transformations.html",
  background = "",
  youtube = ""
)

design_matrices_1 <- list(
  title = "Design matrices",
  topics = c("Models in matrix form", "Regression", "Multiple regression"),
  pdf = "",
  rmd = "lectures/week_04/lec_10_design_matrices.Rmd",
  html = "lectures/week_04/lec_10_design_matrices.html",
  background = "",
  youtube = ""
)

design_matrices_2 <- list(
  title = "Design matrices",
  topics = c("ANOVA", "ANCOVA"),
  pdf = "",
  rmd = "lectures/week_04/lec_11_design_matrices.Rmd",
  html = "lectures/week_04/lec_11_design_matrices.html",
  background = "",
  youtube = ""
)

max_likelihood <- list(
  title = "Maximum likelihood",
  topics = c("Relationship to probability", "Estimation", "Ratio tests"),
  pdf = "",
  rmd = "lectures/week_04/lec_12_max_likelihood.Rmd",
  html = "lectures/week_04/lec_12_max_likelihood.html",
  background = "",
  youtube = ""
)

model_selection_1 <- list(
  title = "Model selection",
  topics = c("Bias-Variance trade-offs", "In-sample selection", "AIC"),
  pdf = "",
  rmd = "lectures/week_05/lec_13_model_selection.Rmd",
  html = "lectures/week_05/lec_13_model_selection.html",
  background = "",
  youtube = ""
)

model_selection_2 <- list(
  title = "Model selection",
  topics = c("Out-of-sample selection", "Cross-validation", "Multi-model inference"),
  pdf = "",
  rmd = "lectures/week_05/lec_14_model_selection.Rmd",
  html = "lectures/week_05/lec_14_model_selection.html",
  background = "",
  youtube = ""
)

mixed_models_1 <- list(
  title = c("Mixed effects models", "<br><b>Project plan due</b>"),
  topics = c("Fixed vs Random effects", "Costs/benefits", "Restricted maximum likelihood"),
  pdf = "",
  rmd = "lectures/week_05/lec_15_intro_mixed_effects.Rmd",
  html = "lectures/week_05/lec_15_intro_mixed_effects.html",
  background = "",
  youtube = ""
)

mixed_models_2 <- list(
  title = "Mixed effects models",
  topics = c("Inference", "Diagnostics", "Model selection"),
  pdf = "",
  rmd = "lectures/week_06/lec_16_mixed_effects.Rmd",
  html = "lectures/week_06/lec_16_mixed_effects.html",
  background = "",
  youtube = ""
)

guest_lec_01 <- list(
  title = "Guest lecture",
  topics = c("Dr. Staci Amburgey"),
  pdf = "",
  rmd = "",
  html = "lectures/week_06/lec_17_guest_lec_amburgey.html",
  background = "",
  youtube = ""
)

intro_GLM <- list(
  title = "Introduction to GLMs",
  topics = c("Data distrbution", "Links", "Linear predictors"),
  pdf = "",
  rmd = "lectures/week_06/lec_18_intro_GLMs.Rmd",
  html = "lectures/week_06/lec_18_intro_GLMs.html",
  background = "",
  youtube = ""
)

binary_GLM <- list(
  title = "Modeling binary data",
  topics = c("Logistic regression", "Model selection", "Diagnostics"),
  pdf = "",
  rmd = "lectures/week_07/lec_19_modeling_binary_data.Rmd",
  html = "lectures/week_07/lec_19_modeling_binary_data.html",
  background = "",
  youtube = ""
)

overdispersed_binary <- list(
  title = "Overdispersion in binary data",
  topics = c("Variance inflation", "Beta-binomial modes", "Quasi-likelihood"),
  pdf = "",
  rmd = "lectures/week_07/lec_20_overdispersed_binary_data.Rmd",
  html = "lectures/week_07/lec_20_overdispersed_binary_data.html",
  background = "",
  youtube = ""
)

count_GLM <- list(
  title = "Modeling count data",
  topics = c("Poisson regression", "Leverage and influence", "Diagnostics"),
  pdf = "",
  rmd = "lectures/week_07/lec_21_modeling_count_data.Rmd",
  html = "lectures/week_07/lec_21_modeling_count_data.html",
  background = "",
  youtube = ""
)

overdispersed_count <- list(
  title = "Overdispersion in count data",
  topics = c("Variance inflation", "QAIC", "Negative-binomial distribution", "Quasi-likelihood"),
  pdf = "",
  rmd = "lectures/week_08/lec_22_modeling_count_data.Rmd",
  html = "lectures/week_08/lec_22_modeling_count_data.html",
  background = "",
  youtube = ""
)

intro_GLMM_1 <- list(
  title = "Introduction to GLMMs",
  topics = c("Computing likelihoods", "Diagnostics", "Goodness-of-fit"),
  pdf = "",
  rmd = "lectures/week_08/lec_23_intro_GLMMs.Rmd",
  html = "lectures/week_08/lec_23_intro_GLMMs.html",
  background = "",
  youtube = ""
)

intro_GLMM_2 <- list(
  title = "More on GLMMs",
  topics = c("Computing likelihoods", "Daignostics", "Goodness-of-fit"),
  pdf = "",
  rmd = "lectures/week_08/lec_24_intro_GLMMs.Rmd",
  html = "lectures/week_08/lec_24_intro_GLMMs.html",
  background = "",
  youtube = ""
)

holiday <- list(
  title = "<b>Memorial Day - No class</b>",
  topics = "",
  pdf = "",
  rmd = "",
  html = "",
  background = "",
  youtube = ""
)

review <- list(
  title = "Material review",
  topics = c("Catchup and review materials"),
  pdf = "",
  rmd = "lectures/week_09/lec_26_review.Rmd",
  html = "lectures/week_09/lec_26_review.html",
  background = "",
  youtube = ""
)

synthesis <- list(
  title = "Course synthesis",
  topics = c("What did we learn?", "Where do we go from here?"),
  pdf = "",
  rmd = "lectures/week_09/lec_27_course_summary.Rmd",
  html = "lectures/week_09/lec_27_course_summary.html",
  background = "",
  youtube = ""
)

present <- list(
  title = "Presentations of class projects",
  topics = "",
  pdf = "",
  rmd = "",
  html = "",
  background = "",
  youtube = ""
)
```



