---
title: "2019 List of Lectures"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
## review of matrix math
matrixlab <- list(
  title = "Matrix math in R",
  topics = c("Matrices & matrix algebra"),
  pdf = "homework/week_01/basic-matrix-math.pdf",
  rmd = "",
  html = "",
  data = "",
  key = ""
  )

## 1 overview of R Markdown
markdown <- list(
  title = "R Markdown",
  topics = c("Authoring reports with R Markdown"),
  pdf = "homework/week_01/hw_01_intro_to_markdown.pdf",
  rmd = "homework/week_01/hw_01_intro_to_markdown.Rmd",
  html = "",
  data = "",
  key = "homework/week_01/hw_01_intro_to_markdown_key.pdf"
)

## 2 fitting linear models
linear_models <- list(
  title = "Fitting linear models",
  topics = c("Fitting linear models"),
  pdf = "homework/week_02/hw_02_fitting_lm.pdf",
  rmd = "homework/week_02/hw_02_fitting_lm.Rmd",
  html = "",
  data = "homework/week_02/L_Washington_plankton.csv",
  key = "homework/week_02/hw_02_fitting_lm_key.pdf"
)

## 3 diagnostics
diagnostics <- list(
  title = "Checking model diagnostics",
  topics = c("Checking model diagnostics"),
  pdf = "homework/week_03/hw_03_diagnostics.pdf",
  rmd = "homework/week_03/hw_03_diagnostics.Rmd",
  html = "",
  data = "homework/week_03/usfws_bull_trout.csv",
  key = "homework/week_03/hw_03_diagnostics_key.pdf"
)

## 4 pvalues
pvalues <- list(
  title = "Considering significance tests",
  topics = c("Thinking about significance tests"),
  pdf = "homework/week_04/hw_04_pvalues_revisited.pdf",
  rmd = "homework/week_04/hw_04_pvalues_revisited.Rmd",
  html = "",
  data = "references/Wasserstein_2019_world_beyond_p05.pdf",
  key = "homework/week_04/hw_04_pvalues_revisited_key.pdf"
)

## 5 model selection
model_selection <- list(
  title = "Model selection & multimodel inference",
  topics = "Model selection & multimodel inference",
  pdf = "homework/week_05/hw_05_model_selection.pdf",
  rmd = "homework/week_05/hw_05_model_selection.Rmd",
  html = "",
  data = "homework/week_05/soil_nitrogen.csv",
  key = "homework/week_05/hw_05_model_selection_key.pdf"
)

## 6 mixed models
mixed_models <- list(
  title = "Fitting mixed models",
  topics = "Fitting mixed models",
  pdf = "homework/week_06/hw_06_mixed_models.pdf",
  rmd = "homework/week_06/hw_06_mixed_models.Rmd",
  html = "",
  data = "homework/week_06/ps_chinook.csv",
  key = "homework/week_06/hw_06_mixed_models_key.pdf"
)

## 7 logistic regr
logistic_regr <- list(
  title = "Fitting logistic regression models",
  topics = "Fitting logistic regression models",
  pdf = "homework/week_07/hw_07_logistic_regr.pdf",
  rmd = "homework/week_07/hw_07_logistic_regr.Rmd",
  html = "",
  data = "homework/week_07/srss_chin_sar.csv",
  key = "homework/week_07/hw_07_logistic_regr_key.pdf"
)

## 8 count models
count_models <- list(
  title = "Models for count data",
  topics = "Models for count data",
  pdf = "homework/week_08/hw_08_count_models.pdf",
  rmd = "homework/week_08/hw_08_count_models.Rmd",
  html = "",
  data = "homework/week_08/plant_richness.csv",
  key = ""
)

```

