---
title: "2019 List of Lectures"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
intro <- list(
  title = "Introduction",
  topics = c("<b>Course overview</b>"),
  rmd = c("lectures/week_01/lec_01_class_overview.Rmd"),
  html = c("lectures/week_01/lec_01_class_overview.html"),
  background = c("[R software](https://www.r-project.org/about.html)",
                 "[RStudio](https://resources.rstudio.com/)",
                 "[Intro to R Markdown](https://rmarkdown.rstudio.com/lesson-1.html)"),
  zoom = ""
)

data_types <- list(
  title = "Ecological data and distributions",
  topics = c("<b>Ecological data & distributions</b>", "Detections", "Counts", "Survival"),
  rmd = c("lectures/week_01/lec_02_data_types.Rmd"),
  html = c("lectures/week_01/lec_02_data_types.html"),
  background = c("[Understanding data](https://punkrockor.com/2019/11/01/data-science-isnt-just-data-wrangling-and-data-analysis-on-understanding-your-data/)",
                 "[Statistical distributions](https://richarddmorey.github.io/stat-distributions-js/)",
                 "[Distribution relationships](http://www.math.wm.edu/~leemis/chart/UDR/UDR.html)"),
  zoom = ""
)

linear_models_1 <- list(
  title = "Linear models",
  topics = c("<b>Linear models</b>", "Non-linear approximations", "Regression, ANOVA, ANCOVA"),
  rmd = c("lectures/week_02/lec_03_intro_to_linear_models.Rmd"),
  html = c("lectures/week_02/lec_03_intro_to_linear_models.html"),
  background = c("[Farraway (2015) Chap 2](references/Faraway_2015_Linear_models_with_R.pdf)"),
  zoom = ""
)

linear_models_2 <- list(
  title = "Linear models",
  topics = c("<b>Linear models</b>", "Models in matrix form", "Least squares", "Identifiability"),
  rmd = c("lectures/week_02/lec_04_intro_to_linear_models.Rmd"),
  html = c("lectures/week_02/lec_04_intro_to_linear_models.html"),
  background = c("[Farraway (2015) Chap 2](references/Faraway_2015_Linear_models_with_R.pdf)"),
  zoom = ""
)

inference_1 <- list(
  title = "Inference",
  topics = c("<b>Inference</b>", "Variance partitioning", "Sum of squares"),
  rmd = c("lectures/week_02/lec_05_inference_from_linear_models.Rmd"),
  html = c("lectures/week_02/lec_05_inference_from_linear_models.html"),
  background = c("[Farraway (2015) Chap 3](references/Faraway_2015_Linear_models_with_R.pdf)",
                 "[Farraway (2015) Chap 4](references/Faraway_2015_Linear_models_with_R.pdf)",
                 "[Wasserstein et al. (2019)](references/Wasserstein_2019_world_beyond_p05.pdf)"),
  zoom = ""
)

inference_2 <- list(
  title = "Inference",
  topics = c("<b>Inference</b>", "F-tests for nested models", "Confidence intervals"),
  rmd = c("lectures/week_02/lec_06_inference_from_linear_models.Rmd"),
  html = c("lectures/week_02/lec_06_inference_from_linear_models.html"),
  background = c("[Farraway (2015) Chap 3](references/Faraway_2015_Linear_models_with_R.pdf)",
                 "[Farraway (2015) Chap 4](references/Faraway_2015_Linear_models_with_R.pdf)",
                 "[Wasserstein et al. (2019)](references/Wasserstein_2019_world_beyond_p05.pdf)"),
  zoom = ""
)

diagnostics_1 <- list(
  title = "Model diagnostics",
  topics = c("<b>Model diagnostics</b>", "Assumptions about errors", "Leverage", "Outliers"),
  rmd = c("lectures/week_03/lec_07_diagnostics_for_linear_models.Rmd"),
  html = c("lectures/week_03/lec_07_diagnostics_for_linear_models.html"),
  background = c("[Farraway (2015) Chap 6](references/Faraway_2015_Linear_models_with_R.pdf)"),
  zoom = ""
)

diagnostics_2 <- list(
  title = "Model diagnostics",
  topics = c("<b>Model diagnostics</b>", "Assumptions about errors", "Unusual observations", "Influential observations"),
  rmd = c("lectures/week_03/lec_07_diagnostics_for_linear_models.Rmd"),
  html = c("lectures/week_03/lec_07_diagnostics_for_linear_models.html"),
  background = c("[Farraway (2015) Chap 6](references/Faraway_2015_Linear_models_with_R.pdf)"),
  zoom = ""
)

non_IID_errors <- list(
  title = "Problems with model residuals",
  topics = c("<b>Problems with model errors</b>", "Generalized least squares", "Weighted least squares", "Robust regression"),
  rmd = "lectures/week_03/lec_08_problems_with_errors.Rmd",
  html = "lectures/week_03/lec_08_problems_with_errors.html",
  background = "[Farraway (2015) Chap 8](references/Faraway_2015_Linear_models_with_R.pdf)",
  zoom = ""
)

transformations <- list(
  title = "Data transformations",
  topics = c("<b>Data transformations</b>", "Box-Cox", "Powers/roots", "Logarithms"),
  rmd = "lectures/week_03/lec_09_data_transformations.Rmd",
  html = "lectures/week_03/lec_09_data_transformations.html",
  background = c("[Farraway (2015) Chap 9](references/Faraway_2015_Linear_models_with_R.pdf)",
                 "[O'Hara & Kotze (2010)](references/OHara_Kotze_2010_dont_log_counts.pdf)",
                 "[Xiao et al. (2011)](references/Xiao_2011_log_vs_NL_regr.pdf)"),
  zoom = ""
)

design_matrices_1 <- list(
  title = "Design matrices",
  topics = c("<b>Design matrices</b>", "Models in matrix form", "Regression", "ANOVA / ANCOVA"),
  rmd = c("lectures/week_04/lec_10_design_matrices.Rmd"),
  html = c("lectures/week_04/lec_10_design_matrices.html"),
  background = "[Venables (2018)](references/Venables_2018_design_matrices.pdf)",
  zoom = ""
)

design_matrices_2 <- list(
  title = "Design matrices",
  topics = c("<b>Design matrices</b>", "Models in matrix form", "Regression", "ANOVA / ANCOVA"),
  rmd = c("lectures/week_04/lec_11_design_matrices.Rmd"),
  html = c("lectures/week_04/lec_11_design_matrices.html"),
  background = "[Venables (2018)](references/Venables_2018_design_matrices.pdf)",
  zoom = ""
)

max_likelihood <- list(
  title = "Maximum likelihood estimation",
  topics = c("<b>Maximum likelihood estimation</b>", "Relationship to probability", "Estimation", "Characteristics of MLE"),
  rmd = "lectures/week_04/lec_12_max_likelihood.Rmd",
  html = "lectures/week_04/lec_12_max_likelihood.html",
  background = "[Faraway (2016) Appendix A](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)",
  zoom = ""
)

model_selection_1 <- list(
  title = "Model selection",
  topics = c("<b>Model selection</b>", "Bias-Variance trade-offs", "In-sample selection", "AIC"),
  rmd = c("lectures/week_05/lec_13_model_selection.Rmd"),
  html = c("lectures/week_05/lec_13_model_selection.html"),
  background = c("[Burnham & Anderson (2002)](references/Burnham_Anderson_2002_model_selection.pdf)",
                 "[Hobbs & Hilborn (2006)](references/Hobbs_Hilborn_2006_alternatives_nht.pdf)"),
  zoom = ""
)

model_selection_2 <- list(
  title = "Model selection",
  topics = c("<b>Model selection</b>", "Out-of-sample selection", "Cross-validation", "Multi-model inference"),
  rmd = c("lectures/week_05/lec_14_model_selection.Rmd"),
  html = c("lectures/week_05/lec_14_model_selection.html"),
  background = c("[Aho et al (2014)](references/Aho_2014_model_selection.pdf)",
                 "[Banner & Higgs (2017)](references/Banner_Higgs_2017_model_averaging.pdf)",
                 "[Burnham & Anderson (2002)](references/Burnham_Anderson_2002_model_selection.pdf)",
                 "[Cade (2015)](references/Cade_2015_muddled_multimodel.pdf)",
                 "[Hooten & Hobbs (2015)](references/Hooten_Hobbs_2015_Bayesian_model_avg.pdf)",
                 "[Link & Barber (2006)](references/Link_Barber_2006_model_weights.pdf)"),
  zoom = ""
)

review <- list(
  title = "Review session",
  topics = c("<b>Review session</b>", "All topics to date"),
  rmd = c(""),
  html = c(""),
  background = "",
  zoom = ""
)

mixed_models_1 <- list(
  title = c("Mixed effects models", "<br><b>Project plan due</b>"),
  topics = c("<b>Mixed effects models</b>", "Fixed vs Random effects", "Shrinkage",
             "Costs/benefits"),
  rmd = "lectures/week_06/lec_16_intro_mixed_effects.Rmd",
  html = "lectures/week_06/lec_16_intro_mixed_effects.html",
  background = c("[Freeman's visualization](http://mfviz.com/hierarchical-models/)",
                 "[Harrison et al (2018)](references/Harrison_2018_intro_mixed_models.pdf)",
                 "[Zuur et al (2009) Chap 5](references/Zuur_2009_mixed_effects_models_in_R.pdf)"),
  zoom = ""
)

mixed_models_2 <- list(
  title = "Mixed effects models",
  topics = c("<b>Mixed effects models</b>", "Inference", "Diagnostics", "Model selection"),
  rmd = "lectures/week_06/lec_17_mixed_effects.Rmd",
  html = "lectures/week_06/lec_17_mixed_effects.html",
  background = c("[Gurka (2006)](references/Gurka_2006_reml.pdf)",
                 "[Harrison et al (2018)](references/Harrison_2018_intro_mixed_models.pdf)"),
  zoom = ""
)

paper_discussion <- list(
  title = "Guest: Dr. Sarah Converse",
  topics = c("<b>Guest discussion</b>", "<b>Dr. Sarah Converse</b>", "<i>Research questions, hypotheses & predictions</i>"),
  rmd = "lectures/week_06/lec_18_paper_discussion.Rmd",
  html = "lectures/week_06/lec_18_paper_discussion.html",
  background = c("[Chamberlin (1890)](references/Chamberlin_1890_multiple-working-hypotheses.pdf)",
                 "[Garton et al (2020)](references/Garton_2020_research-design.pdf)"),
  zoom = ""
)

intro_GLM <- list(
  title = "Introduction to GLMs",
  topics = c("<b>Introduction to GLMs</b>", "Data distributions", "Link functions", "Linear predictors"),
  rmd = c("lectures/week_07/lec_19_intro_GLMs.Rmd"),
  html = c("lectures/week_07/lec_19_intro_GLMs.html"),
  background = c("[Nelder & Wedderburn (1972)](references/Nelder_Wedderburn_1972_GLM.pdf)",
                 "[Faraway (2016) Chap 8](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)"),
  zoom = ""
)

binary_GLM <- list(
  title = "Modeling binary data",
  topics = c("<b>Modeling binary data</b>", "Logistic regression", "Model selection",
             "Diagnostics", "<br><b>Project plan due</b>"),
  rmd = "lectures/week_07/lec_20_modeling_binary_data.Rmd",
  html = "lectures/week_07/lec_20_modeling_binary_data.html",
  background = "[Faraway (2016) Chap 2](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)",
  zoom = ""
)

overdispersed_binary <- list(
  title = "Overdispersion in binary data",
  topics = c("<b>Overdispersion in binary data</b>", "Variance inflation", "Beta-binomial modes", "Quasi-likelihood"),
  rmd = "lectures/week_07/lec_21_overdispersed_binary_data.Rmd",
  html = "lectures/week_07/lec_21_overdispersed_binary_data.html",
  background = c("[Faraway (2016) Chap 2 & 3](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)"),
  zoom = ""
)

count_GLM <- list(
  title = "Modeling count data",
  topics = c("<b>Modeling count data</b>", "Poisson regression", "Leverage and influence", "Diagnostics"),
  rmd = "lectures/week_08/lec_22_modeling_count_data.Rmd",
  html = "lectures/week_08/lec_22_modeling_count_data.html",
  background = c("[Faraway (2016) Chap 5](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)", "[St-Pierre et al. (2017)](references/StPierre_2017_count_data_in_biology.pdf)"),
  zoom = ""
)

overdispersed_count <- list(
  title = "Overdispersion in count data",
  topics = c("<b>Overdispersion in count data</b>", "Variance inflation", "Quasi-likelihood", "Negative-binomial distribution"),
  rmd = c("lectures/week_08/lec_23_overdispersed_count_data.Rmd"),
  html = c("lectures/week_08/lec_23_overdispersed_count_data.html"),
  background = c("[Faraway (2016) Chap 5](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)", "[Ver Hoef & Boveng (2007)](references/VerHoef_Boveng_2007_quasiPois_vs_negbin.pdf)"),
  zoom = ""
)

zero_models <- list(
  title = "Zero-truncated & zero-inflated models",
  topics = c("<b>Zero-truncated & zero-inflated models</b>", "Zero truncation", "Zero inflation", "Hurdle models", "Mixture models"),
  rmd = c("lectures/week_08/lec_24_zero_models.Rmd"),
  html = c("lectures/week_08/lec_24_zero_models.html"),
  background = c("[Faraway (2016) Chap 5](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)",
                 "[Zuur et al (2009) Chap 11](references/Zuur_2009_mixed_effects_models_in_R.pdf)",
                 "[Blasco-Moreno (2019)](references/Blasco-Moreno_2019_what_does_a_zero_mean.pdf.pdf)"),
  zoom = ""
)

holiday <- list(
  title = "<b>Memorial Day - No class</b>",
  topics = "<b>Memorial Day - No class</b>",
  rmd = "",
  html = "",
  background = "",
  zoom = ""
)

intro_GLMM_1 <- list(
  title = "Working with GLMMs",
  topics = c("<b>Working with GLMMs</b>", "Computing likelihoods"),
  rmd = c("lectures/week_09/lec_26_intro_GLMMs.Rmd"),
  html = c("lectures/week_09/lec_26_intro_GLMMs.html"),
  background = c("[Faraway (2016) Chap 13](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)",
                 "[Zuur et al (2009) Chap 13](references/Zuur_2009_mixed_effects_models_in_R.pdf)",
                 "[Bolker et al (2009)](Bolker_2009_glmm_guide.pdf)"),
  zoom = ""
)

intro_GLMM_2 <- list(
  title = "Working with GLMMs",
  topics = c("<b>Working with GLMMs</b>", "Diagnostics", "Goodness-of-fit"),
  rmd = c("lectures/week_09/lec_27_intro_GLMMs.Rmd"),
  html = c("lectures/week_09/lec_27_intro_GLMMs.html"),
  background = c("[Faraway (2016) Chap 13](references/Faraway_2016_Extending_the_Linear_Models_with_R.pdf)",
                 "[Zuur et al (2009) Chap 13](references/Zuur_2009_mixed_effects_models_in_R.pdf)",
                 "[Bolker et al (2009)](Bolker_2009_glmm_guide.pdf)"),
  zoom = ""
)


intro_GAM_1 <- list(
  title = "Intro to GAMs",
  topics = c("<b>Intro to GAMs</b>", "Smooths"),
  rmd = c("lectures/week_10/lec_28_intro_GAMs.Rmd"),
  html = c("lectures/week_10/lec_28_intro_GAMs.html"),
  background = c("[Zuur et al (2009) Chap 3](references/Zuur_2009_mixed_effects_models_in_R.pdf)",
                 "[Pedersen et al (2019)](references/Pedersen_2019_hierarchical_gam.pdf)"),
  zoom = ""
)

intro_GAM_2 <- list(
  title = "Working with GLMMs",
  topics = c("<b>Working with GAMs</b>", "Fitting models"),
  rmd = c("lectures/week_10/lec_29_intro_GAMs.Rmd"),
  html = c("lectures/week_10/lec_29_intro_GAMs.html"),
  background = c("[Zuur et al (2009) Chap 3](references/Zuur_2009_mixed_effects_models_in_R.pdf)",
                 "[Pedersen et al (2019)](references/Pedersen_2019_hierarchical_gam.pdf)"),
  zoom = ""
)

synthesis <- list(
  title = "Course synthesis",
  topics = c("<b>Course synthesis</b>", "What did we learn?", "Where do we go from here?"),
  rmd = c("lectures/week_10/lec_30_course_summary.Rmd"),
  html = c("lectures/week_10/lec_30_course_summary.html"),
  background = "",
  zoom = ""
)


## old stuff below here

software <- list(
  title = "Overview of required software",
  topics = c("<b>Required software</b>","R / RStudio", "R Markdown", "GitHub"),
  rmd = c("lectures/week_01/lec_02_software.Rmd"),
  html = c("lectures/week_01/lec_02_software.html"),
  background = c("[R software](https://www.r-project.org/about.html)",
                 "[RStudio](https://resources.rstudio.com/)",
                 "[Intro to R Markdown](https://rmarkdown.rstudio.com/lesson-1.html)",
                 "[Video intro to GitHub](https://www.youtube.com/watch?v=w3jLJU7DT5E)"),
  zoom = ""
)

review_2 <- list(
  title = "Material review",
  topics = c("<b>Review of materials</b>"),
  rmd = c(""),
  html = c(""),
  background = "",
  zoom = ""
)

present_1 <- list(
  title = "Presentations of class projects",
  topics = "<b>Presentations of class projects</b>",
  rmd = "",
  html = "lectures/week_10/lec_28_present_1.html",
  background = "",
  zoom = "https://washington.zoom.us/rec/share/y_BJLozX3DxOXYnLzlDdZv8iGqTaX6a81HMe-PsInkacvB1GYhj-vY1J1YFKNK03"
)

present_2 <- list(
  title = "Presentations of class projects",
  topics = "<b>Presentations of class projects</b>",
  rmd = "",
  html = "lectures/week_10/lec_29_present_2.html",
  background = "",
  zoom = "https://washington.zoom.us/rec/share/1PVofo_Tp21JTKvvy06cU4gAMKXVeaa8hnIdrvcLzU2QzOitTtXXdfLjfobJvcGD"
)

present_3 <- list(
  title = "Presentations of class projects",
  topics = "<b>Presentations of class projects</b>",
  rmd = "",
  html = "lectures/week_10/lec_30_present_3.html",
  background = "",
  zoom = "https://washington.zoom.us/rec/share/1elUEI2vtUhOe6_gtRrheqo9GNviaaa82ygeq6EMnxlgFaKnlZXkqzIVvhivTP6s"
)

guest_lec_01 <- list(
  title = "Guest lecture - Dr. Staci Amburgey",
  topics = c("<b>Guest lecture:</b>", "<b>Dr. Staci Amburgey</b>", "<i>Using quantitative ecology for<br>species conservation in the<br>face of anthropogenic change</i>"),
  rmd = "",
  html = "lectures/week_06/lec_17_guest_lec_amburgey.html",
  background = c("[Amburgey et al (2017)](references/Amburgey_2017_GCB)",
                 "[Amburgey et al (2019)](references/Amburgey_2019_Ecosphere)",
                 "[Amburgey et al (2020)](references/Amburgey_2020_JHerp)"),
  zoom = ""
)
```



