---
title: "QERM 514<br>Analysis of Ecological and Environmental Data"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---



<br>

# Course overview

This course is intended to introduce students to a large class of statistical models that form the basis for a large majority of statistical analyses conducted in ecology and environmental science. They include simple linear models, such as analysis of variance (ANOVA) and regression models, along with Generalized Linear Models (GLMs) and Generalized Linear Mixed Models (GLMMs), which assume non-normal error distributions (_e.g._, logistic and Poisson regression). Students will also learn the differences between fixed and random effects. In particular, we will focus on conceptualizing analyses, implementing analyses, and making inference from the results.

<br>

# Learning objectives

By the end of the quarter, students should be able to:

* Identify an appropriate statistical model based on the data and specific question

* Understand the assumptions behind a chosen statistical model

* Use **R** to fit a variety of linear models to data

* Evaluate data support for various models and select the most parsimonious model among them

* Use **R Markdown** to combine text, equations, code, tables, and figures into reports

<br>

# Instructor

[**Mark Scheuerell**](https://fish.uw.edu/faculty/mark-scheuerell/)  
Associate Professor, School of Aquatic & Fishery Sciences

Office: Rm 220A Fishery Sciences

Email: [qerm514@uw.edu](mailto:qerm514@uw.edu)

<br>

# Meeting times & locations

#### Lectures 
M/W/F from 10:30-11:20 ~~in FSH 213~~ via [Zoom](https://washington.zoom.us/j/831083365)

#### Computer Lab
Friday from 11:30-1:20 ~~in FSH 136~~ via [Zoom](https://washington.zoom.us/j/946943308)

#### Office hours
By appointment

<br>

# Pre-requisites

Students should be comfortable with basic probability and statistics. Students should also have a working knowledge of the [**R**](https://www.r-project.org/) computing software, such as that provided in FISH 552/553.

<br>

# Technology

This course will revolve around hands-on computing exercises that demonstrate the topics of interest. Therefore, students are strongly recommended to bring their own laptop to class, although students are certainly free to work with one another. **For students without access to a personal laptop**: it is possible to check out UW laptops for an entire quarter (see the [Student Services office](https://education.uw.edu/admissions/office-of-student-services) for details).

All of the software we will be using is free and platform independent, meaning students may use macOS, Linux, or Windows operating systems. In addition to a web browser, we will be using the free [**R**](https://www.r-project.org/) software and the desktop version of the [**R Studio**](https://www.rstudio.com/products/rstudio-desktop/) integrated development environment (IDE). We will also be using various packages not contained in the base installation of **R**, but we will wait and install them at the necessary time. The instructor will be available during the first week of class to help students troubleshoot any software installation problems.

<br>

# Teaching methodology

This course will introduce new material primarily through prepared slides and hands-on demonstrations. Students will be expected to work both individually and collaboratively (to the extent possible given the current conditions); course content and evaluation will emphasize the communication of ideas and the ability to think critically more so than a specific pathway or method. Other areas of this website provide an overview of the topics to be covered, including links to weekly reading assignments, lecture materials, computer labs, and homework assignments.

<br>

# Evaluation

Students will be evaluated on their knowledge of course content, and their ability to communicate their understanding of the material, via individual homework assignments (70%) and a final project (30%). There will be 8 homework assignments, but the lowest score will be dropped for the purposes of grading; each of the 7 highest scoring assignments will count toward 10% of the final grade. Please note, though, that **all eight homework assignments must be turned in to achieve a passing grade**. Homework will be assigned each Friday of weeks 1-8 and will be due by 11:59 PM one week later on the following Friday (weeks 2-9). The instructor will evaluate and return student homework assignments within one week of their due date. **If for some reason you cannot meet the homework deadline, contact the instructor as soon as possible to discuss other options**.

Each student will complete a final project consisting of three elements: 1) a project plan, 2) a project presentation, and 3) a project report. The project plan will be due by 11:59 PM on Friday, May 1. Presentations of student projects will occur during the last week of class; specific days/times will be assigned randomly. The final project will be due by 11:59 PM on Sunday, June 7. Please see the [Final Project](final_proj.html) page for more details.

Students should discuss any potential schedule conflicts with the instructor during the first week of class.

<br>

# Communication

This course will involve a *lot* of communication between and among students and the instructor. Short questions should be addressed to me via email; I will try my best to respond to your message within 24 hours. Under more normal circumstances, detailed questions would be addressed to me in person--either after class or during a scheduled meeting. In this case, however, we will schedule one-on-one or group Zoom calls as needed. As the course progresses, we will also use some online tools for larger discussions and comments.

<br>

# Access & accommodations

All students deserve access to the full range of learning experiences, and the University of Washington is committed to creating inclusive and accessible learning environments consistent with federal and state laws. 


### Disabilities

If you have already established accommodations with Disability Resources for Students (DRS), please communicate your approved accommodations to me at your earliest convenience so we can discuss your needs in this course. If you have not yet established services through DRS, but have a temporary health condition or permanent disability that requires accommodations (*e.g.*, mental health, learning, vision, hearing, physical impacts), you are welcome to contact DRS at 206-543-8924 or via [email](mailto:uwdrs@uw.edu) or their [website](https://depts.washington.edu/uwdrs/). DRS offers resources and coordinates reasonable accommodations for students with disabilities and/or temporary health conditions.  Reasonable accommodations are established through an interactive process between you, your instructor(s) and DRS.


### Religious observances

Students who expect to miss class or assignments as a consequence of their religious observance will be provided with a reasonable accommodation to fulfill their academic responsibilities. Absence from class for religious reasons does not relieve students from responsibility for the course work required during the period of absence. It is the responsibility of the student to provide the instructor with advance notice of the dates of religious holidays on which they will be absent. Students who are absent will be offered an opportunity to make up the work, without penalty, within a reasonable time, as long as the student has made prior arrangements.

<br>

# Academic integrity

Faculty and students at the University of Washington are expected to maintain the highest standards of academic conduct, professional honesty, and personal integrity (see the [University of Washington Student Conduct Code](https://www.washington.edu/cssc/for-students/academic-misconduct/)). Plagiarism, cheating, and other academic misconduct are serious violations of the Student Conduct Code. I have no reason to believe that anyone will violate the Student Conduct Code, but *I will have no choice* but to refer any suspected violation(s) to the College of the Environment for a Student Conduct Process hearing. Students who have been guilty of a violation will receive zero points for the assignment in question.

<br>

# Classroom conduct

I am dedicated to providing a welcoming and supportive environment for all people, regardless of background or identity. Any form of language or behavior used to exclude, intimidate, or cause discomfort will not be tolerated. This applies to all course participants (instructor, students, guests). In order to foster a positive and professional learning environment, I encourage the following kinds of behaviors:

* Use welcoming and inclusive language

* Be respectful of different viewpoints and experiences

* Gracefully accept constructive criticism

* Show courtesy and respect towards others

**Please note**: If you believe you have been a victim of an alleged violation of the Student Conduct Code or you are aware of an alleged violation of the Student Conduct Code, you have the right to [report it to the University](https://www.washington.edu/cssc/for-students-2/).

<br>

# Safety

If you feel unsafe or at-risk in any way while taking any course, contact [SafeCampus](https://www.washington.edu/safecampus/) (206-685-7233) anytime&ndash;no matter where you work or study&ndash;to anonymously discuss safety and well-being concerns for yourself or others. SafeCampus can provide individualized support, discuss short- and long-term solutions, and connect you with additional resources when requested. For a broader range of resources and assistance see the [Husky Health & Well-Being website](https://wellbeing.uw.edu/).

<br>

# Food Pantry

No student should ever have to choose between buying food or textbooks. The UW Food Pantry helps mitigate the social and academic effects of campus food insecurity. They aim to lessen the financial burden of purchasing food by providing students access to shelf-stable groceries, seasonal fresh produce, and hygiene products at **no cost**. Students can expect to receive 4 to 5 days' worth of supplemental food support when they visit the Pantry, located on the north side of Poplar Hall at the corner of NE 41<sup>st</sup> St and Brooklyn Ave NE. Visit the [Any Hungry Husky website](https://uw.edu/anyhungryhusky) for additional information, including operating hours and additional food support resources.

