---
title: "Lecture information"
output: html_document
---

<br>

**Navigating slide decks in `.html` format:**

* Use the arrow keys (&#8592;/&#8594;) on your keyboard to go forward or backward

* Press the "o" key on any slide to show you an overview of the slide deck

* In overview mode, click on a slide or press "esc" to zoom in on it


```{r child = "_timeline.Rmd", include=FALSE}
```

```{r child = "_list_of_lectures.Rmd", include=FALSE}
```

```{r week_lecs, include = FALSE}
## empty list for lecs
week_lecs <- vector("list", 30)
names(week_lecs) <- paste0("L", seq(30))
## lecture topics
## week 1
week_lecs$L1 <- intro
week_lecs$L2 <- data_types
week_lecs$L3 <- linear_models_1
## week 2
week_lecs$L4 <- linear_models_2
week_lecs$L5 <- inference_1
week_lecs$L6 <- inference_2
## week 3
week_lecs$L7 <- diagnostics_1
week_lecs$L8 <- diagnostics_2
week_lecs$L9 <- non_IID_errors
## week 4
week_lecs$L10 <- transformations
week_lecs$L11 <- design_matrices_1
week_lecs$L12 <- max_likelihood
## week 5
week_lecs$L13 <- model_selection_1
week_lecs$L14 <- model_selection_2
week_lecs$L15 <- review
## week 6
week_lecs$L16 <- mixed_models_1
week_lecs$L17 <- mixed_models_2
week_lecs$L18 <- paper_discussion
## week 7
week_lecs$L19 <- intro_GLM
week_lecs$L20 <- binary_GLM
week_lecs$L21 <- overdispersed_binary
## week 8
week_lecs$L22 <- count_GLM
week_lecs$L23 <- overdispersed_count
week_lecs$L24 <- zero_models
## week 9
week_lecs$L25 <- holiday
week_lecs$L26 <- intro_GLMM
week_lecs$L27 <- more_GLMM
## week 10
week_lecs$L28 <- intro_GAM
week_lecs$L29 <- more_GAM
week_lecs$L30 <- synthesis
```

```{r topics, include = FALSE, eval = FALSE}
lec_titles <- lapply(week_lecs, function(x) { if(is.list(x)) {x$title} else {""} })
## topics formatted for html
lec_titles_html <- sapply(lapply(lec_titles, paste, "<br>", collapse = ""), c)
names(lec_titles_html) <- NULL
```

```{r lecture_topics, include = FALSE}
lec_topics <- lapply(week_lecs, function(x) { if(is.list(x)) {x$topics} else {""} })
## topics formatted for html
lec_topics_html <- sapply(lapply(lec_topics, paste, "<br>", collapse = ""), c)
names(lec_topics_html) <- NULL
```

```{r lec_links_orig, include = FALSE, eval = FALSE}
## HTML
slide_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$html)} else {""} })
slide_links_html <- sapply(lapply(slide_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-alt", height = "2em", fill = "#eb6864")),
                   " (", 1:length(x), ") notes](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-alt", height = "2em", fill = "#eb6864")),
                     " notes](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)

# slide_links_html <- sapply(slide_links_html, sub, 
#                            pattern = 'role', replacement = 'aria-labelledby=\"link\" role')               
               
## Rmd
source_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$rmd)} else {""} })
source_links_html <- sapply(lapply(source_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-code", height = "2em", fill = "#eb6864")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-code", height = "2em", fill = "#eb6864")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1,x,tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)

source_links_html <- sapply(source_links_html, sub, 
                            pattern = 'role', replacement = 'aria-labelledby=\"link\" role')               

## PDF
pdf_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$pdf)} else {""} })
pdf_links_html <- sapply(lapply(pdf_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-pdf", height = "2em", fill = "#eb6864")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-pdf", height = "2em", fill = "#eb6864")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)

pdf_links_html <- sapply(source_links_html, 
                         sub, pattern = 'role', replacement = 'aria-labelledby=\"link\" role')
```

```{r lec_links, include = FALSE}
## HTML
slide_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$html)} else {""} })
slide_links_html <- sapply(lapply(slide_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[html (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[html](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)

# slide_links_html <- sapply(slide_links_html, sub, 
#                            pattern = 'role', replacement = 'aria-labelledby=\"link\" role')               
               
## Rmd
source_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$rmd)} else {""} })
source_links_html <- sapply(lapply(source_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[Rmd (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[Rmd](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1,x,tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)

# source_links_html <- sapply(source_links_html, sub, 
#                             pattern = 'role', replacement = 'aria-labelledby=\"link\" role')               

## PDF
pdf_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$pdf)} else {""} })
pdf_links_html <- sapply(lapply(pdf_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[pdf (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[pdf](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)

# pdf_links_html <- sapply(source_links_html, 
#                          sub, pattern = 'role', replacement = 'aria-labelledby=\"link\" role')
```

```{r zoom_links, include = FALSE, eval = FALSE}
zoom_links <- lapply(week_lecs, function(x) { if(is.list(x)) {x$zoom} else {""} })
## topics formatted for html
zoom_links_html <- sapply(lapply(zoom_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-video", height = "2em", a11y = "sem", fill = "#eb6864")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-video", height = "2em", a11y = "sem", fill = "#eb6864")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)
```

```{r youtube_links, include = FALSE, eval = FALSE}
youtube_links <- lapply(week_lecs, function(x) { if(is.list(x)) {x$youtube} else {""} })
## topics formatted for html
youtube_links_html <- sapply(lapply(youtube_links, function(x) {
  tmp1 <- "[YouTube]("; tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)
names(youtube_links_html) <- NULL
```

```{r background_links, include = FALSE}
background_links <- lapply(week_lecs, function(x) { if(is.list(x)) {x$background} else {""} })
## topics formatted for html
background_links_html <- sapply(lapply(background_links, paste, "<br>", collapse = ""), c)
names(background_links_html) <- NULL
```

```{r generate_table, echo=FALSE}
## data frame with dates & topics
syl_txt <- data.frame(
  date = qtr,
  # lec_titles = lec_titles_html,
  lec_topics = lec_topics_html,
  lec_links = slide_links_html,
  rmd_links = source_links_html,
  # pdf_links = pdf_links_html,
  # zoom_links = zoom_links_html,
  # youtube_links = youtube_links_html,
  background_links = background_links_html
)
colnames(syl_txt) <- c("Date", "Topic(s)",
                       "Slides", "Source", # "Slides (pdf)",
                       # "Zoom recording",
                       "Background info")
rownames(syl_txt) <- NULL

## generate table
kableExtra::kable(syl_txt, format = "html", caption = " ",
                  align = "clccc", escape = FALSE) %>%
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE,
                position = "left") %>%
  column_spec(c(1,3,4), width = "6em") %>%
  column_spec(5, width = "17em") %>%
  scroll_box(height = "700px", extra_css = "border-style: none;")
```

