---
title: "Syllabus"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

<br>

# Course overview

This course will introduce students to a large class of statistical models commonly used for analyses in ecology and environmental science. These include simple linear models, such as analysis of variance (ANOVA) and regression models, along with Generalized Linear Models (GLMs) that assume non-normal error distributions (_e.g._, logistic and Poisson regression). Students will learn to distinguish the difference between fixed and random effects, and how to implement them in mixed-effects models such as Generalized Linear Mixed Models (GLMMs). This course also covers various aspects of assessing model performance and evaluating model diagnostics. In general, students will focus on conceptualizing analyses, implementing analyses, and making inference from the results.

This course is also one of the core requirements for graduate students in the Quantitative Ecology & Resource Management (QERM) program at the University of Washington. For more information, [click here](https://quantitative.uw.edu/graduate/).

<br>

# Learning objectives

By the end of the quarter, students should be able to:

* Identify an appropriate statistical model based on the data and specific question

* Understand the assumptions behind a chosen statistical model

* Use **R** to fit a variety of linear models to data

* Evaluate data support for various models and select the most parsimonious model among them

* Use **R Markdown** to combine text, equations, code, tables, and figures into reports

<br>

# Instructor

[**Mark Scheuerell**](https://fish.uw.edu/faculty/mark-scheuerell/), Associate Professor, School of Aquatic & Fishery Sciences

Office: Rm 220A Fishery Sciences

Email: [scheuerl@uw.edu](mailto:scheuerl@uw.edu)

<br>

# Meeting times & locations

**Lectures**

M/W/F from 10:30-11:20 in FSH 213

**Computer Lab**

Friday from 11:30-1:20 in FSH 136

**Office hours**

M from 11:30-12:30 in FSH 220A

<br>

# Pre-requisites

Students should be comfortable with basic probability and statistics. Students should also have a working knowledge of the [**R**](https://www.r-project.org/) computing software, such as that provided in FISH 552/553.

<br>

# Classroom conduct

I am dedicated to providing a welcoming and supportive environment for all people, regardless of background, identity, physical appearance, or manner of communication. Any form of language or behavior used to exclude, intimidate, or cause discomfort will not be tolerated. This applies to all course participants (instructor, students, guests). In order to foster a positive and professional learning environment, I encourage the following kinds of behaviors:

* Use welcoming and inclusive language

* Be respectful of different viewpoints and experiences

* Gracefully accept constructive criticism

* Show courtesy and respect towards others

**Please note**: If you believe you have been a victim of an alleged violation of the [Student Conduct Code](https://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html) or you are aware of an alleged violation of the [Student Conduct Code](https://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html), you have the right to [report it to the University](https://www.washington.edu/cssc/for-students-2/).

<br>

# Access & accommodations

All students deserve access to the full range of learning experiences, and the University of Washington is committed to creating inclusive and accessible learning environments consistent with federal and state laws. 

## Disabilities

If you have already established accommodations with Disability Resources for Students (DRS), please communicate your approved accommodations to me at your earliest convenience so we can discuss your needs in this course. If you have not yet established services through DRS, but have a temporary health condition or permanent disability that requires accommodations (*e.g.*, mental health, learning, vision, hearing, physical impacts), you are welcome to contact DRS at 206-543-8924 or via [email](mailto:uwdrs@uw.edu) or their [website](https://depts.washington.edu/uwdrs/). DRS offers resources and coordinates reasonable accommodations for students with disabilities and/or temporary health conditions.  Reasonable accommodations are established through an interactive process between you, your instructor(s) and DRS.

## Religious observances

Students who expect to miss class or assignments as a consequence of their religious observance will be provided with a reasonable accommodation to fulfill their academic responsibilities. Absence from class for religious reasons does not relieve students from responsibility for the course work required during the period of absence. It is the responsibility of the student to provide the instructor with advance notice of the dates of religious holidays on which they will be absent. Students who are absent will be offered an opportunity to make up the work, without penalty, within a reasonable time, as long as the student has made prior arrangements.

<br>

# Technology

This course will revolve around hands-on computing exercises that demonstrate the topics of interest. Therefore, students are strongly recommended to bring their own laptop to class, although students are certainly free to work with one another. **For students without access to a personal laptop**: it is possible to check out UW laptops for an entire quarter (see the [Student Services office](https://education.uw.edu/admissions/office-of-student-services) for details).

All of the software we will be using is free and platform independent, meaning students may use macOS, Linux, or Windows operating systems. In addition to a web browser, we will be using the free [**R**](https://www.r-project.org/) software and the desktop version of the [**R Studio**](https://www.rstudio.com/products/rstudio-desktop/) integrated development environment (IDE). We will also be using various packages not contained in the base installation of **R**, but we will wait and install them at the necessary time. The instructor will be available during the first week of class to help students troubleshoot any software installation problems.

<br>

# Teaching methodology

This course will introduce new material primarily through prepared slides and hands-on demonstrations. Students will be expected to work both individually and collaboratively (to the extent possible given the current conditions); course content and evaluation will emphasize the communication of ideas and the ability to think critically more than a specific pathway or method. Other areas of this website provide an overview of the topics to be covered, including links to weekly reading assignments, lecture materials, computer labs, homework assignments, and the final project.

<br>

# Communication

This course will involve a *lot* of communication between and among students and the instructor. Short questions should be addressed to me via email; I will try my best to respond to your message within 24 hours. More detailed questions should be addressed to me in person--either during office hours or a scheduled meeting.

<br>

# Evaluation

Students will be evaluated on their knowledge of course content and their ability to communicate their understanding of the material via quizzes (25%), homework assignments (40%) and a final project (35%). Students should discuss any potential schedule conflicts with the instructor during the first week of class.

## Quizzes

Because course content builds in complexity, quizzes are an important tool for both of us to check that you are understanding foundational concepts. Quizzes will be a mix of multiple choice and short answer questions. Quizzes will be assigned every Monday of weeks 2 - 8 (i.e., seven total over the course of the quarter), and they will be available on Canvas from 8:00 AM PDT until 10:00 PM PDT (14 hours). **NOTE**: Each quiz must be completed and submitted within 30 minutes from the time you begin so plan accordingly.

I will drop your two lowest quiz grades, such that the remaining five will each constitute 5% of your final grade for the course. As such, I will not give make-up quizzes or accept quizzes submitted after the deadline (25% total). I recommend doing your best on all quizzes because you never know when you may need to miss one unexpectedly. **NOTE**: Quizzes are the only part of the course work that must be completed entirely independently; you may not work with other students on quizzes.

## Homework

There will be four homework assignments that will require you to go into more depth than quizzes. Homework problems will typically require you to build a model based on information and data provided, fit the model, and interpret the results. Homework will be assigned each Friday of weeks 2, 4, 6 & 8, and will be due by 11:59 PM PDT on the following Sunday *nine* days later. Students will use R Markdown for their homework assignment and submit them as pdf documents.

Each homework assignment will constitute 10% of your final course grade (40% total). Please see the [Homework](homework.html) page for more details. **NOTE**: Students may consult with their fellow classmates on homework problems, but each student must submit their own assignment that reflects their own work.

## Final Project

Each student will complete a final project consisting of two elements: a project plan (10%) and a project report (25%). The project plan will be due no later than 11:59 PM PDT on Sunday, May 10. The final project will be due no later than 11:59 PM PDT on Wednesday, June 10. Students will use R Markdown for their final report and submit it as a pdf document. Please see the [Final Project](final_proj.html) page for more details.

<br>

# Use of Artificial Intelligence (AI)

In this course, students are permitted to use AI-based tools (such as ChatGPT) on some assignments. The instructions for each assignment will include information about whether and how you may use AI-based tools to complete the assignment. All sources, including AI tools, must be properly cited. Use of AI in ways that are inconsistent with the parameters above will be considered academic misconduct and subject to investigation.

Please note that AI results can be biased and inaccurate. It is your responsibility to ensure that the information you use from AI is accurate. Additionally, pay attention to the privacy of your data. Many AI tools will incorporate and use any content you share, so be careful not to unintentionally share copyrighted materials, original work, or personal information.

_If you have any questions about citation or about what constitutes academic integrity in this course or at the University of Washington, please feel free to contact me to discuss your concerns._

<br>

# Academic integrity

Faculty and students at the University of Washington are expected to maintain the highest standards of academic conduct, professional honesty, and personal integrity. Plagiarism, cheating, and other academic misconduct are serious violations of the [Student Conduct Code](https://www.washington.edu/cssc/for-students/academic-misconduct/). I have no reason to believe that anyone will violate the Student Conduct Code, but *I will have no choice* but to refer any suspected violation(s) to the College of the Environment for a Student Conduct Process hearing. Students who have been guilty of a violation will receive zero points for the assignment in question.

<br>

# Mental health

We are in the midst of an historic pandemic that is creating a variety of challenges for everyone. If you should feel like you need some help, please consider the following resources available to students.

**If you are experiencing a life-threatening emergency, please dial 911**.  

[**Crisis Clinic**](http://www.crisisclinic.org/)  
Phone: 206-461-3222 or toll-free at 1-866-427-4747   

[**UW Counseling Center**](https://www.washington.edu/counseling/services)  
Phone: 206-543-1240  
[Immediate assistance](https://www.washington.edu/counseling/services/crisis/)

[**Let’s Talk**](https://wellbeing.uw.edu/virtual-lets-talk/)

[**Hall Health Mental Health**](https://wellbeing.uw.edu/unit/hall-health)

<br>

# Safety

If you feel unsafe or at-risk in any way while taking any course, contact [SafeCampus](https://www.washington.edu/safecampus/) (206-685-7233) anytime&ndash;no matter where you work or study&ndash;to anonymously discuss safety and well-being concerns for yourself or others. SafeCampus can provide individualized support, discuss short- and long-term solutions, and connect you with additional resources when requested. For a broader range of resources and assistance see the [Husky Health & Well-Being website](https://wellbeing.uw.edu/).

<br>

# Food Pantry

No student should ever have to choose between buying food or textbooks. The UW Food Pantry helps mitigate the social and academic effects of campus food insecurity. They aim to lessen the financial burden of purchasing food by providing students access to shelf-stable groceries, seasonal fresh produce, and hygiene products at **no cost**. Students can expect to receive 4 to 5 days' worth of supplemental food support when they visit the Pantry, located on the north side of Poplar Hall at the corner of NE 41<sup>st</sup> St and Brooklyn Ave NE. Visit the [Any Hungry Husky website](https://uw.edu/anyhungryhusky) for additional information, including operating hours and additional food support resources.

<br>

<center>*This site was last updated at `r format(Sys.time(), "%H:%M")` on `r format(Sys.Date(), "%d %b %Y")`*</center>

