---
title: "Ecological data & distributions"
subtitle: "Analysis of Ecological and Environmental Data<br>QERM 514"
author: "Mark Scheuerell"
date: "3 April 2026"
output:
  ioslides_presentation:
    widescreen: true
    css: lecture_slides.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Goals for today

* Identify features of data that drive analyses

> - Think critically about what the data *could* tell you


## General approach

### Question $\rightarrow$ Data $\rightarrow$ Model $\rightarrow$ Inference $\rightarrow$ Prediction


## General approach

### <u>Question</u> $\rightarrow$ Data $\rightarrow$ Model $\rightarrow$ Inference $\rightarrow$ Prediction


## Common questions in ecology | At the individual level

### Sex?

### Fecundity?

### Growth? 

### Survival?

### Movement?


## Common questions in ecology | At the population level

### Abundance?

### Survival?

### Spatial distribution? 

### Movement/migration?


## General approach

### Question $\rightarrow$ <u>Data</u> $\rightarrow$ Model $\rightarrow$ Inference $\rightarrow$ Prediction


## Ecological data | At the individual level

### 1 Detection $\rightarrow$ presence/absence

### 2+ Detections $\rightarrow$ survival, movement


## Ecological data | At the individual level

### 1 Detection $\rightarrow$ presence/absence

### 2+ Detections $\rightarrow$ survival, movement

<br>

### 1 Measurement $\rightarrow$ fecundity, age, size

### 2+ Measurements $\rightarrow$ growth


## Ecological data | At the population level

### Detections $\rightarrow$ presence/absence

<br>

### Counts $\rightarrow$ density or survival/movement


## Data collection methods

### Nonexhaustive counts


## &nbsp; {data-background=pelagic_trawl.jpg data-background-size=100%}


## Data collection methods

### Exhaustive counts


## &nbsp; {data-background=weir.JPG data-background-size=cover}


## Data collection methods

### (Non)exhaustive surveys

### Depletions


## &nbsp; {data-background=electrofishing.jpg data-background-size=cover}


## Data collection methods

### (Non)exhaustive surveys

### Depletions

### Capture/Tag/Recapture


## &nbsp; {data-background=sparrow.jpg data-background-size=65%}


## Data types | Discrete values

### Sex

### Age

### Fecundity

### Counts/Census

### Survival (individual)


## Data types | Continuous

### Size (length, mass)

### Density

### Survival (population)


## A note on continuous variables | Approximating rational numbers with real numbers

### Survival (7 of 9 survived $\approx$ 0.78)

<br>

### Composition (4 age-3, 18 age-4, 11 age-5 $\rightarrow$ ~55% age-4)

<br>

### Density (3 animals in 21 ha plot $\approx$ 0.14 per ha)


## A note on continuous variables | Approximating rational numbers with real numbers

### Which of these give you more confidence?

### A) 3 / 9 $\approx$ 0.33

### B) 300 / 900 $\approx$ 0.33


## {.flexbox .vcenter .bigger}

<font size="10">
<center>The importance of raw data cannot be overstated</center>
</font>

## {.flexbox .vcenter .bigger}

<font size="10">
Distributions of data 
</font>


## Discrete distributions

### Binary (0,1) $\rightarrow$ [Bernoulli](https://en.wikipedia.org/wiki/Bernoulli_distribution)


## Discrete distributions

### Binary (0,1) $\rightarrow$ [Bernoulli](https://en.wikipedia.org/wiki/Bernoulli_distribution)

<br>

### Count (non-negative integers) $\rightarrow$ [Poisson](https://en.wikipedia.org/wiki/Poisson_distribution) or [Negative-Binomial](https://en.wikipedia.org/wiki/Negative_binomial_distribution)


## Discrete distributions

### Binary (0,1) $\rightarrow$ [Bernoulli](https://en.wikipedia.org/wiki/Bernoulli_distribution)

<br>

### Count (non-negative integers) $\rightarrow$ [Poisson](https://en.wikipedia.org/wiki/Poisson_distribution) or [Negative-Binomial](https://en.wikipedia.org/wiki/Negative_binomial_distribution)

<br>

### Composition (length-D counts) $\rightarrow$ [Binomial](https://en.wikipedia.org/wiki/Binomial_distribution) (*D* = 2) or [Multinomial](https://en.wikipedia.org/wiki/Multinomial_distribution) (*D* > 2)


## Continuous distributions

### Density (non-negative real values) $\rightarrow$ [log-Normal](https://en.wikipedia.org/wiki/Log-normal_distribution) or [Gamma](https://en.wikipedia.org/wiki/Gamma_distribution)


## Continuous distributions

### Density (non-negative real values) $\rightarrow$ [log-Normal](https://en.wikipedia.org/wiki/Log-normal_distribution) or [Gamma](https://en.wikipedia.org/wiki/Gamma_distribution)

<br>

### Proportion (length-D simplex) $\rightarrow$ [Beta](https://en.wikipedia.org/wiki/Beta_distribution) (*D* = 2) or [Dirichlet](https://en.wikipedia.org/wiki/Dirichlet_distribution) (*D* > 2)


## Continuous distributions

### Density $\left(\mathbb{R}^{\geq}\right)$ $\rightarrow$ [log-Normal](https://en.wikipedia.org/wiki/Log-normal_distribution) or [Gamma](https://en.wikipedia.org/wiki/Gamma_distribution)

<br>

### Proportion (simplex$^D$) $\rightarrow$ [Beta](https://en.wikipedia.org/wiki/Beta_distribution) (*D* = 2) or [Dirichlet](https://en.wikipedia.org/wiki/Dirichlet_distribution) (*D* > 2)

<br>

### Transformations (real values) $\rightarrow$ [Normal](https://en.wikipedia.org/wiki/Normal_distribution)


